### PR TITLE
Interactive

### PR DESCRIPTION
**Pull request by Yordinia**
- [ ] Added a new JavaScript file and import it as a module: checkstate.js, class setState.
- [ ] AAdded a new JavaScript file and import it as a module: checkstate.js, class setState.
- [ ] Added event listener to the checkbox (change).
- [ ] Update items object's value for completed key upon user actions.
- [ ] Implement a function for the "Clear all completed" button (use filter() method).
- [ ] Store the updated array of items in local storage.
- [ ] Added a new JavaScript file and import it as a module: checkstate.js, class setState.
- [ ] Added event listener to the checkbox (change).
- [ ] Update items object's value for completed key upon user actions.
- [ ] Implement a function for the "Clear all completed" button (use filter() method).dded event listener to the checkbox (change).
- [ ] Update items object's value for completed key upon user actions.
- [ ] Implement a function for the "Clear all completed" button (use filter() method).
- [ ] Store the updated array of items in local storage.
- [ ] Added a new JavaScript file and import it as a module: checkstate.js, class setState.
- [ ] Added event listener to the checkbox (change).
- [ ] Update items object's value for completed key upon user actions.
- [ ] Implement a function for the "Clear all completed" button (use filter() method).
- [ ] 
- [ ] Store the updated array of items in local storage.

### CODE REVIEW

**Comment by codecaiine** [comment]
@Yordinia ... what is your slack name please

**Comment by Yordinia** [comment]
hi

**Comment by Yordinia** [comment]
this is my slack email ***@***.***

**Comment by Yordinia** [comment]
I also wanted  advice on something. because of electricity issues, i
couldn't finish my projects on time. Thus, I wanted extra time for the last
features of this week's project. To whom do I mail this to. I couldn't find
student success email pelase. If you could help.

**Comment by Yordinia** [comment]
@codecaiine are you there perhaps its too late for me

**Review by Munsa1 — APPROVED** [review]
Hi @Yordinia, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
